"""Add new models and modify existing models for gym management features

Revision ID: 0f70844f6ff9
Revises: f0bef507b334
Create Date: 2026-01-19 09:04:23.116212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f70844f6ff9'
down_revision = 'f0bef507b334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('purchaser_name', sa.String(length=100), nullable=True),
    sa.Column('purchaser_phone', sa.String(length=20), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed_by_member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bridge_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('computer_name', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('os_info', sa.String(length=100), nullable=True),
    sa.Column('database_path', sa.String(length=500), nullable=True),
    sa.Column('database_found', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('total_syncs', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_class_booking', sa.Boolean(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_closings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('new_subscriptions_count', sa.Integer(), nullable=True),
    sa.Column('renewals_count', sa.Integer(), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('card_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('transfer_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_cash_submitted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_difference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_expenses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('difference_explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'branch_id', 'closing_date', name='unique_daily_closing')
    )
    op.create_table('gym_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotional_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('min_subscription_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('applicable_service_type_id', sa.Integer(), nullable=True),
    sa.Column('applicable_plan_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicable_plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['applicable_service_type_id'], ['service_types.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('reason_type', sa.String(length=20), nullable=False),
    sa.Column('reason_details', sa.Text(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_by', sa.Integer(), nullable=True),
    sa.Column('expected_resume_date', sa.Date(), nullable=True),
    sa.Column('resumed_at', sa.DateTime(), nullable=True),
    sa.Column('resumed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['resumed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stopped_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['gym_classes.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tracking_token', sa.String(length=32), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['complaint_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_token')
    )
    op.create_table('device_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('command_type', sa.String(length=50), nullable=False),
    sa.Column('target_emp_id', sa.String(length=20), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('command_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('metabolic_rate', sa.Float(), nullable=True),
    sa.Column('daily_calories', sa.Float(), nullable=True),
    sa.Column('ideal_weight', sa.Float(), nullable=True),
    sa.Column('weight_difference', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('status_message', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renewal_rejections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gym_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pool_capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_gym_occupancy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_pool_occupancy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lease_expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('commercial_registration_expiry', sa.Date(), nullable=True))

    with op.batch_alter_table('employee_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fingerprint_log_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('expected_check_in', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('late_minutes', sa.Integer(), nullable=True))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_expenses_approved_by', 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_income_service_type_id', 'service_types', ['service_type_id'], ['id'])

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_staff', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('staff_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_members_staff_user_id', 'users', ['staff_user_id'], ['id'])

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('freeze_is_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('freeze_daily_rate', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('requires_class_booking', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_plans_service_type_id', 'service_types', ['service_type_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_complaints', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_complaints', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_daily_closing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_daily_closing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_classes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_approve_expenses', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_offers', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_gift_cards', sa.Boolean(), nullable=True))

    with op.batch_alter_table('subscription_freezes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('offer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('offer_discount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('gift_card_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gift_card_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stop_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stopped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('stopped_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_subscriptions_service_type_id', 'service_types', ['service_type_id'], ['id'])
        batch_op.create_foreign_key('fk_subscriptions_stopped_by', 'users', ['stopped_by'], ['id'])
        batch_op.create_foreign_key('fk_subscriptions_offer_id', 'promotional_offers', ['offer_id'], ['id'])
        batch_op.create_foreign_key('fk_subscriptions_gift_card_id', 'gift_cards', ['gift_card_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fingerprint_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_trainer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('is_trainer')
        batch_op.drop_column('fingerprint_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscriptions_gift_card_id', type_='foreignkey')
        batch_op.drop_constraint('fk_subscriptions_offer_id', type_='foreignkey')
        batch_op.drop_constraint('fk_subscriptions_stopped_by', type_='foreignkey')
        batch_op.drop_constraint('fk_subscriptions_service_type_id', type_='foreignkey')
        batch_op.drop_column('stopped_by')
        batch_op.drop_column('stopped_at')
        batch_op.drop_column('stop_reason')
        batch_op.drop_column('gift_card_amount')
        batch_op.drop_column('gift_card_id')
        batch_op.drop_column('offer_discount')
        batch_op.drop_column('offer_id')
        batch_op.drop_column('service_type_id')

    with op.batch_alter_table('subscription_freezes', schema=None) as batch_op:
        batch_op.drop_column('fee_amount')
        batch_op.drop_column('is_paid')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('can_manage_gift_cards')
        batch_op.drop_column('can_manage_offers')
        batch_op.drop_column('can_approve_expenses')
        batch_op.drop_column('can_manage_classes')
        batch_op.drop_column('can_manage_daily_closing')
        batch_op.drop_column('can_view_daily_closing')
        batch_op.drop_column('can_manage_complaints')
        batch_op.drop_column('can_view_complaints')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plans_service_type_id', type_='foreignkey')
        batch_op.drop_column('requires_class_booking')
        batch_op.drop_column('freeze_daily_rate')
        batch_op.drop_column('freeze_is_paid')
        batch_op.drop_column('service_type_id')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_members_staff_user_id', type_='foreignkey')
        batch_op.drop_column('staff_user_id')
        batch_op.drop_column('is_staff')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('height_cm')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint('fk_income_service_type_id', type_='foreignkey')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('service_type_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_approved_by', type_='foreignkey')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('status')

    with op.batch_alter_table('employee_attendance', schema=None) as batch_op:
        batch_op.drop_column('late_minutes')
        batch_op.drop_column('expected_check_in')
        batch_op.drop_column('source')
        batch_op.drop_column('fingerprint_log_id')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('commercial_registration_expiry')
        batch_op.drop_column('lease_expiry_date')
        batch_op.drop_column('current_pool_occupancy')
        batch_op.drop_column('current_gym_occupancy')
        batch_op.drop_column('pool_capacity')
        batch_op.drop_column('gym_capacity')

    op.drop_table('renewal_rejections')
    op.drop_table('health_reports')
    op.drop_table('device_commands')
    op.drop_table('complaints')
    op.drop_table('class_bookings')
    op.drop_table('subscription_stops')
    op.drop_table('promotional_offers')
    op.drop_table('gym_classes')
    op.drop_table('daily_closings')
    op.drop_table('service_types')
    op.drop_table('bridge_status')
    op.drop_table('gift_cards')
    op.drop_table('complaint_categories')
    # ### end Alembic commands ###
