"""Add branch_code to Branch, branch_id to fingerprint models

Revision ID: 8843c681fd29
Revises: 994ef56af55e
Create Date: 2026-04-30 08:09:22.143389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8843c681fd29'
down_revision = '994ef56af55e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_code', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_branch_code', ['branch_code'])

    with op.batch_alter_table('bridge_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_bridge_settings_branch', ['branch_id'])
        batch_op.create_foreign_key('fk_bridge_settings_branch', 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('bridge_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bridge_status_branch', 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('device_commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_device_commands_branch', 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('fingerprint_sync_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sync_logs_branch', 'branches', ['branch_id'], ['id'])

    # Generate branch_codes for existing branches: BR-{brand_id}-{branch_id}
    op.execute("UPDATE branches SET branch_code = 'BR-' || brand_id || '-' || id WHERE branch_code IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fingerprint_sync_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('device_commands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('bridge_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('bridge_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('branch_code')

    # ### end Alembic commands ###
