"""Add fingerprint to Branch, add brand_finance role

Revision ID: 994ef56af55e
Revises: a1b2c3d4e5f6
Create Date: 2026-04-29 08:07:28.378261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994ef56af55e'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # Add fingerprint fields to branches
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses_fingerprint', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fingerprint_ip', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('fingerprint_port', sa.Integer(), nullable=True))

    # Copy fingerprint data from brand to its branches
    op.execute("""
        UPDATE branches SET
            uses_fingerprint = (SELECT uses_fingerprint FROM brands WHERE brands.id = branches.brand_id),
            fingerprint_ip = (SELECT fingerprint_ip FROM brands WHERE brands.id = branches.brand_id),
            fingerprint_port = (SELECT fingerprint_port FROM brands WHERE brands.id = branches.brand_id)
    """)

    # Add brand_finance role
    op.execute("""
        INSERT INTO roles (name, name_en, description,
            is_owner, can_view_all_brands,
            can_manage_members, can_manage_subscriptions,
            can_view_finance, can_manage_finance,
            can_view_reports, can_manage_attendance,
            can_view_complaints, can_manage_complaints,
            can_view_daily_closing, can_manage_daily_closing,
            can_manage_classes, can_approve_expenses,
            can_manage_offers, can_manage_gift_cards)
        SELECT 'مالية براند', 'brand_finance', 'مالية على مستوى البراند بكل فروعه',
            0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0
        WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name_en = 'brand_finance')
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('fingerprint_port')
        batch_op.drop_column('fingerprint_ip')
        batch_op.drop_column('uses_fingerprint')

    # ### end Alembic commands ###
