"""Add EmployeeShift, BridgeSettings models and member_import_id field

Revision ID: f787e45c0ad3
Revises: e942dff569dc
Create Date: 2026-04-28 10:28:37.414617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f787e45c0ad3'
down_revision = 'e942dff569dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('class_access_window_minutes', sa.Integer(), nullable=True),
    sa.Column('att2000_mdb_path', sa.String(length=500), nullable=True),
    sa.Column('backup_mdb_path', sa.String(length=500), nullable=True),
    sa.Column('attendance_sync_interval', sa.Integer(), nullable=True),
    sa.Column('access_control_interval', sa.Integer(), nullable=True),
    sa.Column('class_access_control_enabled', sa.Boolean(), nullable=True),
    sa.Column('employee_shift_tracking_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_block_expired', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id')
    )
    op.create_table('employee_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('work_start_time', sa.Time(), nullable=False),
    sa.Column('work_end_time', sa.Time(), nullable=False),
    sa.Column('applicable_days', sa.String(length=20), nullable=True),
    sa.Column('late_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_import_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('member_import_id')

    op.drop_table('employee_shifts')
    op.drop_table('bridge_settings')
    # ### end Alembic commands ###
